name: nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.7.0=py36_0
  - asn1crypto=0.24.0=py36_1003
  - astor=0.7.1=py36_0
  - blas=1.0=mkl
  - boto=2.49.0=py36_0
  - boto3=1.9.82=py_0
  - botocore=1.12.82=py_0
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29=py36_0
  - cffi=1.11.5=py36h9745a5d_1001
  - chardet=3.0.4=py36_1003
  - click=7.0=py36_0
  - cryptography=2.5=py36hb7f436b_0
  - cymem=2.0.2=py36hfd86e86_0
  - cytoolz=0.9.0.1=py36h14c3975_1001
  - dill=0.2.9=py36_0
  - docutils=0.14=py36_0
  - flask=1.0.2=py36_1
  - gast=0.2.2=py36_0
  - gensim=3.4.0=py36h14c3975_0
  - grpcio=1.14.1=py36h9ba97e2_0
  - h5py=2.9.0=py36h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - idna=2.8=py36_1000
  - intel-openmp=2019.1=144
  - itsdangerous=1.1.0=py36_0
  - jinja2=2.10=py36_0
  - jmespath=0.9.3=py36_0
  - keras=2.2.4=0
  - keras-applications=1.0.6=py36_0
  - keras-base=2.2.4=py36_0
  - keras-preprocessing=1.0.5=py36_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libprotobuf=3.6.1=hd408876_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - markdown=3.0.1=py36_0
  - markupsafe=1.1.0=py36h7b6447c_0
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py36h14c3975_1
  - mkl_random=1.0.2=py36h637b7d7_2
  - msgpack-numpy=0.4.3.2=py_0
  - msgpack-python=0.6.1=py36h6bb024c_0
  - murmurhash=1.0.0=py36hfc679d8_0
  - ncurses=6.1=he6710b0_1
  - nltk=3.4=py36_1
  - numpy=1.15.4=py36h7e9f1db_0
  - numpy-base=1.15.4=py36hde5b4d6_0
  - openssl=1.0.2p=h14c3975_0
  - pandas=0.24.0=py36he6710b0_0
  - pip=18.1=py36_0
  - plac=0.9.6=py_1
  - preshed=2.0.1=py36he6710b0_0
  - protobuf=3.6.1=py36he6710b0_0
  - pycparser=2.19=py_0
  - pyopenssl=19.0.0=py36_0
  - pysocks=1.6.8=py36_1002
  - python=3.6.6=h6e4f718_2
  - python-dateutil=2.7.5=py36_0
  - pytz=2018.9=py36_0
  - pyyaml=3.13=py36h14c3975_0
  - readline=7.0=h7b6447c_5
  - regex=2018.01.10=py36h14c3975_1000
  - requests=2.21.0=py36_1000
  - s3transfer=0.1.13=py36_0
  - scikit-learn=0.20.2=py36hd81dba3_0
  - scipy=1.2.0=py36h7c811a0_0
  - setuptools=40.6.3=py36_0
  - six=1.12.0=py36_1000
  - smart_open=1.8.0=py36_0
  - spacy=2.0.18=py36hf484d3e_1000
  - sqlite=3.26.0=h7b6447c_0
  - tensorboard=1.12.2=py36he6710b0_0
  - tensorflow=1.12.0=mkl_py36h69b6ba0_0
  - tensorflow-base=1.12.0=mkl_py36h3c3e929_0
  - termcolor=1.1.0=py36_1
  - thinc=6.12.1=py36h637b7d7_1000
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py_1
  - tqdm=4.30.0=py_0
  - ujson=1.35=py36h14c3975_1001
  - urllib3=1.24.1=py36_1000
  - werkzeug=0.14.1=py36_0
  - wheel=0.32.3=py36_0
  - wrapt=1.10.11=py36h14c3975_1001
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - aniso8601==4.1.0
    - en-core-web-sm==2.0.0
    - en-vectors-web-lg==2.0.0
    - flask-restful==0.3.7
prefix: /home/ubuntu/anaconda3/envs/nlp

